### ISSUE TITLE
Story.js missing module module declration

### ISSUE THREAD

**Issue by jqn** [infinitered/ignite-andross#216]
The stories included in this boilerplate are causing hot reload to throw the following error:

`Story of "SomeComponent" named "SomeComponentName" already exists`

This can be easily fixed by adding the module declaration to storiesOf like this

```
 storiesOf('RoundedButton', module)
  .add('Default', () => <RoundedButton text="A simple rounded button" />)
  .add('Text as children', () => (
    <RoundedButton>Hello from the childrens!</RoundedButton>
  )); 
```

<img width="492" alt="screen shot 2018-08-14 at 9 29 44 pm" src="https://user-images.githubusercontent.com/9710893/44158938-51459d00-a073-11e8-988e-47d3e06a0bdd.png">

**Comment by jamonholmgren** [comment]
Is this still happening with 2.4.0?

**Comment by jqn** [comment]
@jamonholmgren I haven't tried the new version. Let me take a look and will report back

**Comment by jqn** [comment]
@jamonholmgren I tried testing the new version but I can't even run storybook. 
This is the error I'm getting
`ERROR in ./storybook/addons.js
Module build failed: Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "/Users/jqn/apps/PizzaAppDec/storybook"`

**Comment by hemel-cse** [comment]
I am getting the error too. 
ERROR in ./storybook/addons.js Module build failed: Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory

**Comment by jamonholmgren** [comment]
Thanks for reporting! Would someone want to submit a PR to fix this? We are focused on Bowser now and not dedicating quite as much time to Andross.

**Comment by erikvdplas** [comment]
Ever found a fix @hemel-cse? The babel-preset still throws an exception for me, and with the react-native preset no stories are shown in storybook.

**Comment by jqn** [comment]
Closing this because it works as expected on new version.
