### ISSUE TITLE
Dev Screens not showing/working

### ISSUE THREAD

**Issue by rudsberg** [infinitered/ignite-andross#222]
Even though opting in for the Ignite Development Screens they are not included. After adding them with "ignite add dev-screens" it fails with the following error:

error: bundling failed: Error: Unable to resolve module `../../ignite/DevScreens/DevscreensButton.js` from `C:\InnoTact\AndrossType\App\Containers\LaunchScreen.js`: The module `../../ignite/DevScreens/DevscreensButton.js` could not be found from `C:\InnoTact\AndrossType\App\Containers\LaunchScreen.js`. Indeed, none of these files exist:

  * `C:\InnoTact\AndrossType\ignite\DevScreens\DevscreensButton.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `C:\InnoTact\AndrossType\ignite\DevScreens\DevscreensButton.js\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (C:\InnoTact\AndrossType\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (C:\InnoTact\AndrossType\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (C:\InnoTact\AndrossType\node_modules\metro\src\node-haste\DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (C:\InnoTact\AndrossType\node_modules\metro\src\DeltaBundler\traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\InnoTact\AndrossType\node_modules\metro\src\DeltaBundler\traverseDependencies.js:374:16)
    at C:\InnoTact\AndrossType\node_modules\metro\src\DeltaBundler\traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (C:\InnoTact\AndrossType\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:313)
    at C:\InnoTact\AndrossType\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:473
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 4.0% (117/651), failed.

My current versions are:
System
  platform           win32
  arch               x64
  cpu                4 cores                        Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz
  directory          C:\InnoTact\AndrossTypeScipt

JavaScript
  node               10.5.0       C:\Program Files\nodejs\node.EXE
  npm                6.1.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.3.2        C:\Users\Joel Rudsberg\AppData\Roaming\npm\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.55.1

Ignite
  ignite             2.1.2        C:\Users\Joel Rudsberg\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\Program Files\Java\jdk1.8.0_172\bin\java.EXE
  android home       -            C:\Users\Joel Rudsberg\AppData\Local\Android\Sdk

**Comment by jamonholmgren** [comment]
@rudsberg Can you try with 2.4.0?

**Comment by jqn** [comment]
@jamonholmgren I just tried version 2.4.0 and indeed the dev screens are directory is missing.

**Comment by jafri** [comment]
still an issue

**Comment by lvlrSajjad** [comment]
@jafri @jqn did you tried installing the boilerplate on a drive other than C ? if you can plz try and tell me the result

**Comment by jafri** [comment]
On MacOS, the problem is LaunchScreen imports a dev screen button, removing that makes the app work.

**Comment by lvlrSajjad** [comment]
@jafri Thanks i will check that is there other issue as well ? other than this import

**Comment by jafri** [comment]
Edit the launchScreen file

**Comment by ystoneman** [comment]
I solved this "ignite add dev-screens" error by deleting the entire directory for this app, and starting over with the following command: `ignite new AppName --boilerplate andross --max`
... instead of `ignite new AppName` or `ignite new AppName -b ir-next` as I had tried before.

**Comment by jamonholmgren** [comment]
@ystoneman Where are you seeing the `ir-next` thing? I want to erase that from our docs.

**Comment by ystoneman** [comment]
@jamonholmgren I saw it on Infinte Red's YouTube channel's video on "[Building a React Native App in Under 15 Minutes](https://youtu.be/lv00UOXxy0g)."

**Comment by jamonholmgren** [comment]
I guess we need a new YouTube video!
