### ISSUE TITLE
StartupRedux should be in reducers in Redux/index.js

### ISSUE THREAD

**Issue by HunWalk** [infinitered/ignite-andross#240]
Hey.
I've recently discovered that StartupRedux is not in the default reducers at App/Redux/index.js
Why is it so? :D

Today i've extended the startupSaga and the startupRedux but after a yield put(StartupActions.startupAction(someData)) nothing happened. Not even a single error.

**Comment by jamonholmgren** [comment]
@GantMan ^^

**Comment by GantMan** [comment]
That Reducer is for actions on app load.   So it's referenced directly here:

https://github.com/infinitered/ignite-andross/blob/master/boilerplate/App/Containers/RootContainer.js#L5

Though it makes sense to include in the index, it's really only meant to dispatch once on application start, and other reducers take it from there.  Moving it to the index is technically correct, but ineffectual.


I hope this helps!
