### ISSUE TITLE
How to access new screen?

### ISSUE THREAD

**Issue by EralpB** [infinitered/ignite-andross#249]
after I create a new screen if I do

initialRouteName: 'NewScreen',

I see the new screen but otherwise I'm stuck at LaunchScreen.

How to add a tabbar to the bottom to switch between pages? Which tutorial should I follow?

Thanks.

**Comment by DenisDov** [comment]
https://reactnavigation.org/docs/en/navigation-prop.html

**Comment by jamonholmgren** [comment]
@DenisDov's is a good link, and here's more info about tabs: https://reactnavigation.org/docs/en/tab-based-navigation.html
