### ISSUE TITLE
Remove Redux from React Navigation Integration

### ISSUE THREAD

**Issue by markwk** [infinitered/ignite-andross#250]
As of React Navigation 3.x, Redux is not the recommended or even working way to handle storing navigation. So as stated here https://reactnavigation.org/docs/en/redux-integration.html, Redux shouldn't be where we store this stuff for navigation. As such, as brought up in #215, we should Remove Redux from React Navigation Integration in this template / boilerplate.

**Comment by ryanlntn** [comment]
As the redux integration represents best practices at IR we will not be removing it. You're more than welcome to fork the boilerplate and modify as much as you want and we'd be happy to add it to the list of third party maintained boilerplates. 😄
