### ISSUE TITLE
Ignite Andross redux-saga Socket.io-client implementation

### ISSUE THREAD

**Issue by mfachmirizal** [infinitered/ignite-andross#251]
Hello, Could someone show me how to use Socket.Io Client using redux-saga on Ignite Andross?..
or should I use socket.io-client inside my Screen ? 
Thanks..

**Comment by ruddell** [comment]
I have used "channels" from redux-saga for a websocket connection. The docs have an example for websockets, look for `eventChannel`: https://redux-saga.js.org/docs/advanced/Channels.html

**Comment by mfachmirizal** [comment]
OK I'll give it a try
Thanks
