### ISSUE TITLE
Redux Action or Screen not refreshing when using DrawerNavigator from React Navigation

### ISSUE THREAD

**Issue by abifdhllh** [infinitered/ignite-andross#254]
I use DrawerNavigator from React Navigation. The structure look like this:

-DrawerNavigator
 --Screen A (InitialRoute)
 --Screen B
 --Screen C

First I'm on Screen A, then I try to move to Screen B, It runs okay with processing the mapDispatchToProps (Redux Action). Then I'm moving from Screen B to Screen A then I'm moving again to Screen B but It didn't refresh the Redux Action and screen not refreshing (Just showing the last Screen B state).

Thank you for the response (Sorry for my bad English).

**Comment by HunWalk** [comment]
Hi. Did you managed to solve the problem? If so, please close this issue.
If not, please provide more information about this. 

Thank you 😊

**Comment by jamonholmgren** [comment]
Hey @abifdhllh , did you happen to fix this?

**Comment by abifdhllh** [comment]
I've solved the issue by adding param **unmountInactiveRoutes** on DrawerNavigator function
