### ISSUE TITLE
Update path for RN-app built with ignite-andross

### ISSUE THREAD

**Issue by timkuilman** [infinitered/ignite-andross#265]
I haven't used the ignite cli or the ignite-andross boilerplate before and I need to update a React Native app that is currently running on RN 0.55.4. 

What does the update path for apps built with this boilerplate looks like? I see that there [was a 3.2.0 release](https://github.com/infinitered/ignite-andross/releases) yesterday that adds support for RN 0.59. Can I update my existing project with the CLI or should I use something like [this](https://pvinis.github.io/purge-web/) and do a manual update?

Thanks in advance for the help!

**Comment by ryanlntn** [comment]
@timkuilman Ignite doesn't handle dependency upgrades so using https://pvinis.github.io/purge-web/ and updating manually is your best bet.
