### ISSUE TITLE
Unable to "yarn run storybook" because of missing deps

### ISSUE THREAD

**Issue by dkocich** [infinitered/ignite-andross#272]
for some reason there are references to missing packages in [addons.js](https://github.com/infinitered/ignite-andross/blob/master/boilerplate/storybook/addons.js)

```
ERROR in ./storybook/addons.js
Module not found: Error: Can't resolve '@storybook/addon-actions/register' in '/home/david/it/xyz-app/storybook'
 @ ./storybook/addons.js 1:0-44
 @ multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js

ERROR in ./storybook/addons.js
Module not found: Error: Can't resolve '@storybook/addon-links/register' in '/home/david/it/xyz-app/storybook'
 @ ./storybook/addons.js 1:45-87
 @ multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js
```

I think that both imports can be removed or packages added to `package.json` to solve the issue:

```
"@storybook/addon-actions": "^5.0.11",
"@storybook/addon-links": "^5.0.11",
```

**Comment by jamonholmgren** [comment]
@dkocich I'd love a PR to fix this!

**Comment by devteam-bold** [comment]
Addons should be same version as @storybook/react-native
    "@storybook/addon-actions": "^4.1.11",
    "@storybook/addon-links": "^4.1.11",

**Comment by acpardal** [comment]
Addons should be same version as "@storybook/react-native": "^4.1.11"

"@storybook/addon-actions": "^4.1.11",
"@storybook/addon-links": "^4.1.11"
