### ISSUE TITLE
reduxsauce is deprecated but still used in ignite-andross

### ISSUE THREAD

**Issue by parthibanloganathan** [infinitered/ignite-andross#281]
Took a look at https://github.com/infinitered/reduxsauce and the project is archived and no longer supported, but it's used in ignite-andross. Is there a recommended alternative or is the move to go with vanilla redux?

**Comment by parthibanloganathan** [comment]
From looking around, `redux-actions` seems to be the prevalent library to reduce boilerplate

**Comment by jamonholmgren** [comment]
We may un-archive it, as I've had some interest in taking it over. Stay tuned.

**Comment by gagandeep** [comment]
@jamonholmgren  I think, project migrated to https://github.com/jkeam/reduxsauce. So, we can close this one.
