### ISSUE TITLE
React native app crash after upgrading to 60 in release mode

### ISSUE THREAD

**Issue by affanhashone** [infinitered/ignite-andross#290]
App crash on upgrading to 60 in release mode

The app crash when changing the bottom tab navigator.

I am using 
Andross version

**Comment by ElieMyIdea** [comment]
Hi,

Are you sure that it doesn't come from Reactotron ? 
I have this issue in release mode : 

`undefined is not an object (evaluating 'console.tron.log'),`

**Comment by ruddell** [comment]
@ElieMyIdea For that issue you can set up `console.tron` in prod to use empty methods.  Here's how [ignite-bowser](https://github.com/infinitered/ignite-bowser/blob/e858ab566d6669cddff6b35a42d0c66a3eca0e07/boilerplate/app/services/reactotron/reactotron.ts#L23-L48) does it

**Comment by ElieMyIdea** [comment]
@ruddell thanks a lot ;)
